apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: opaque
data: 
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_DB: ZmFzdGFwaV9wb3N0Z3Jlc19kb2NrZXI=
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vYWRtaW46YWRtaW5AcG9zdGdyZXMtc2VydmljZTo1NDMyL2Zhc3RhcGlfcG9zdGdyZXNfZG9ja2Vy